# rake db:seed
Group.create(name: 'A')
Group.create(name: 'B')
Group.create(name: 'C')
Group.create(name: 'D')
Group.create(name: 'E')
Group.create(name: 'F')
Group.create(name: 'G')
Group.create(name: 'H')

Team.create(name: 'Brasil')
Team.create(name: 'Croácia')
Team.create(name: 'México')
Team.create(name: 'Camarões')

Team.create(name: 'Austrália')
Team.create(name: 'Chile')
Team.create(name: 'Espanha')
Team.create(name: 'Holanda')

Team.create(name: 'Costa do Marfim')
Team.create(name: 'Grécia')
Team.create(name: 'Colômbia')
Team.create(name: 'Japão')

Team.create(name: 'Uruguai')
Team.create(name: 'Costa Rica')
Team.create(name: 'Inglaterra')
Team.create(name: 'Itália')

Team.create(name: 'Suíça')
Team.create(name: 'Equador')
Team.create(name: 'Honduras')
Team.create(name: 'França')

Team.create(name: 'Bósnia-Herzegóvina')
Team.create(name: 'Argentina')
Team.create(name: 'Nigéria')
Team.create(name: 'Irã')

Team.create(name: 'Alemanha')
Team.create(name: 'Portugal')
Team.create(name: 'Gana')
Team.create(name: 'Estados Unidos')

Team.create(name: 'Coreia do Sul')
Team.create(name: 'Bélgica')
Team.create(name: 'Rússia')
Team.create(name: 'Argélia')

Match.create(datetime: '2014-06-12 17:00:00', team_a: Team.find_by_name('Brasil'), team_b: Team.find_by_name('Croácia'), group: Group.find_by_name('A'))
Match.create(datetime: '2014-06-13 13:00:00', team_a: Team.find_by_name('México'), team_b: Team.find_by_name('Camarões'), group: Group.find_by_name('A'))
Match.create(datetime: '2014-06-17 16:00:00', team_a: Team.find_by_name('Brasil'), team_b: Team.find_by_name('México'), group: Group.find_by_name('A'))
Match.create(datetime: '2014-06-18 19:00:00', team_a: Team.find_by_name('Camarões'), team_b: Team.find_by_name('Croácia'), group: Group.find_by_name('A'))
Match.create(datetime: '2014-06-23 17:00:00', team_a: Team.find_by_name('Camarões'), team_b: Team.find_by_name('Brasil'), group: Group.find_by_name('A'))
Match.create(datetime: '2014-06-23 17:00:00', team_a: Team.find_by_name('Croácia'), team_b: Team.find_by_name('México'), group: Group.find_by_name('A'))

Match.create(datetime: '2014-06-13 16:00:00', team_a: Team.find_by_name('Espanha'), team_b: Team.find_by_name('Holanda'), group: Group.find_by_name('B'))
Match.create(datetime: '2014-06-13 19:00:00', team_a: Team.find_by_name('Chile'), team_b: Team.find_by_name('Austrália'), group: Group.find_by_name('B'))
Match.create(datetime: '2014-06-18 13:00:00', team_a: Team.find_by_name('Austrália'), team_b: Team.find_by_name('Holanda'), group: Group.find_by_name('B'))
Match.create(datetime: '2014-06-18 16:00:00', team_a: Team.find_by_name('Espanha'), team_b: Team.find_by_name('Chile'), group: Group.find_by_name('B'))
Match.create(datetime: '2014-06-23 13:00:00', team_a: Team.find_by_name('Austrália'), team_b: Team.find_by_name('Espanha'), group: Group.find_by_name('B'))
Match.create(datetime: '2014-06-23 13:00:00', team_a: Team.find_by_name('Holanda'), team_b: Team.find_by_name('Chile'), group: Group.find_by_name('B'))

Match.create(datetime: '2014-06-14 13:00:00', team_a: Team.find_by_name('Colômbia'), team_b: Team.find_by_name('Grécia'), group: Group.find_by_name('C'))
Match.create(datetime: '2014-06-14 22:00:00', team_a: Team.find_by_name('Costa do Marfim'), team_b: Team.find_by_name('Japão'), group: Group.find_by_name('C'))
Match.create(datetime: '2014-06-19 13:00:00', team_a: Team.find_by_name('Colômbia'), team_b: Team.find_by_name('Costa do Marfim'), group: Group.find_by_name('C'))
Match.create(datetime: '2014-06-19 19:00:00', team_a: Team.find_by_name('Japão'), team_b: Team.find_by_name('Grécia'), group: Group.find_by_name('C'))
Match.create(datetime: '2014-06-24 17:00:00', team_a: Team.find_by_name('Japão'), team_b: Team.find_by_name('Colômbia'), group: Group.find_by_name('C'))
Match.create(datetime: '2014-06-24 17:00:00', team_a: Team.find_by_name('Grécia'), team_b: Team.find_by_name('Costa do Marfim'), group: Group.find_by_name('C'))

Match.create(datetime: '2014-06-14 16:00:00', team_a: Team.find_by_name('Uruguai'), team_b: Team.find_by_name('Costa Rica'), group: Group.find_by_name('D'))
Match.create(datetime: '2014-06-14 19:00:00', team_a: Team.find_by_name('Inglaterra'), team_b: Team.find_by_name('Itália'), group: Group.find_by_name('D'))
Match.create(datetime: '2014-06-19 16:00:00', team_a: Team.find_by_name('Uruguai'), team_b: Team.find_by_name('Inglaterra'), group: Group.find_by_name('D'))
Match.create(datetime: '2014-06-20 13:00:00', team_a: Team.find_by_name('Itália'), team_b: Team.find_by_name('Costa Rica'), group: Group.find_by_name('D'))
Match.create(datetime: '2014-06-24 13:00:00', team_a: Team.find_by_name('Costa Rica'), team_b: Team.find_by_name('Inglaterra'), group: Group.find_by_name('D'))
Match.create(datetime: '2014-06-24 13:00:00', team_a: Team.find_by_name('Itália'), team_b: Team.find_by_name('Uruguai'), group: Group.find_by_name('D'))

Match.create(datetime: '2014-06-15 13:00:00', team_a: Team.find_by_name('Suíça'), team_b: Team.find_by_name('Equador'), group: Group.find_by_name('E'))
Match.create(datetime: '2014-06-15 16:00:00', team_a: Team.find_by_name('França'), team_b: Team.find_by_name('Honduras'), group: Group.find_by_name('E'))
Match.create(datetime: '2014-06-20 16:00:00', team_a: Team.find_by_name('Suíça'), team_b: Team.find_by_name('França'), group: Group.find_by_name('E'))
Match.create(datetime: '2014-06-20 19:00:00', team_a: Team.find_by_name('Honduras'), team_b: Team.find_by_name('Equador'), group: Group.find_by_name('E'))
Match.create(datetime: '2014-06-25 17:00:00', team_a: Team.find_by_name('Equador'), team_b: Team.find_by_name('Suíça'), group: Group.find_by_name('E'))
Match.create(datetime: '2014-06-25 17:00:00', team_a: Team.find_by_name('Honduras'), team_b: Team.find_by_name('França'), group: Group.find_by_name('E'))

Match.create(datetime: '2014-06-15 19:00:00', team_a: Team.find_by_name('Argentina'), team_b: Team.find_by_name('Bósnia-Herzegóvina'), group: Group.find_by_name('F'))
Match.create(datetime: '2014-06-16 16:00:00', team_a: Team.find_by_name('Irã'), team_b: Team.find_by_name('Nigéria'), group: Group.find_by_name('F'))
Match.create(datetime: '2014-06-21 13:00:00', team_a: Team.find_by_name('Argentina'), team_b: Team.find_by_name('Irã'), group: Group.find_by_name('F'))
Match.create(datetime: '2014-06-21 19:00:00', team_a: Team.find_by_name('Nigéria'), team_b: Team.find_by_name('Bósnia-Herzegóvina'), group: Group.find_by_name('F'))
Match.create(datetime: '2014-06-25 13:00:00', team_a: Team.find_by_name('Nigéria'), team_b: Team.find_by_name('Argentina'), group: Group.find_by_name('F'))
Match.create(datetime: '2014-06-25 13:00:00', team_a: Team.find_by_name('Bósnia-Herzegóvina'), team_b: Team.find_by_name('Irã'), group: Group.find_by_name('F'))

Match.create(datetime: '2014-06-16 13:00:00', team_a: Team.find_by_name('Alemanha'), team_b: Team.find_by_name('Portugal'), group: Group.find_by_name('G'))
Match.create(datetime: '2014-06-16 19:00:00', team_a: Team.find_by_name('Gana'), team_b: Team.find_by_name('Estados Unidos'), group: Group.find_by_name('G'))
Match.create(datetime: '2014-06-21 16:00:00', team_a: Team.find_by_name('Alemanha'), team_b: Team.find_by_name('Gana'), group: Group.find_by_name('G'))
Match.create(datetime: '2014-06-22 19:00:00', team_a: Team.find_by_name('Estados Unidos'), team_b: Team.find_by_name('Portugal'), group: Group.find_by_name('G'))
Match.create(datetime: '2014-06-26 13:00:00', team_a: Team.find_by_name('Portugal'), team_b: Team.find_by_name('Gana'), group: Group.find_by_name('G'))
Match.create(datetime: '2014-06-26 13:00:00', team_a: Team.find_by_name('Estados Unidos'), team_b: Team.find_by_name('Alemanha'), group: Group.find_by_name('G'))

Match.create(datetime: '2014-06-17 13:00:00', team_a: Team.find_by_name('Bélgica'), team_b: Team.find_by_name('Argélia'), group: Group.find_by_name('H'))
Match.create(datetime: '2014-06-17 19:00:00', team_a: Team.find_by_name('Rússia'), team_b: Team.find_by_name('Coreia do Sul'), group: Group.find_by_name('H'))
Match.create(datetime: '2014-06-22 13:00:00', team_a: Team.find_by_name('Bélgica'), team_b: Team.find_by_name('Rússia'), group: Group.find_by_name('H'))
Match.create(datetime: '2014-06-22 16:00:00', team_a: Team.find_by_name('Coreia do Sul'), team_b: Team.find_by_name('Argélia'), group: Group.find_by_name('H'))
Match.create(datetime: '2014-06-26 17:00:00', team_a: Team.find_by_name('Argélia'), team_b: Team.find_by_name('Rússia'), group: Group.find_by_name('H'))
Match.create(datetime: '2014-06-26 17:00:00', team_a: Team.find_by_name('Coreia do Sul'), team_b: Team.find_by_name('Bélgica'), group: Group.find_by_name('H'))